EVALUATION_VOCABULARY = {
    'above-average': 1,
    'angry': -2,
    'acceptable': 1,
    'aggressive': -2,
    'accessible': 1,
    'annoyed': -2,
    'accommodating': 1,
    'annoying': -2,
    'accountable': 2,
    'anxious': -2,
    'anxiously': -2,
    'adjustable': 1,
    'arrogance': -2,
    'advantage': 1,
    'arrogant': -2,
    'advantageous': 1,
    'advantageously': 1,
    'aware': -1,
    'affluent': 2,
    'casual': -1,
    'affordable': 2,
    'affordably': 2,
    'challenging': -1,
    'agile': 1,
    'cheap': -1,
    'amazing': 3,
    'crashing': -3,
    'menable': 1,
    'critical': -3,
    'approachable': 2,
    'riticism': -3,
    'appropriate': 1,
    'deviating': -1,
    'articulate': 1,
    'different': -1,
    'aspirational': 1,
    'difficult': -2,
    'attentive': 1,
    'disappointing': -2,
    'average': 1,
    'disappointment': -2,
    'awareness': 1,
    'disconnected': -1,
    'awesome': 2,
    'discontent':-2,
    'beneficial':2,
    'discouragement':-2,
    'best':3,
    'discouraging':-2,
    'better-documented':1,
    'disgust':-3,
    'bright':1,
    'disgusted':-2,
    'capable':1,
    'disgusting':-3,
    'careful':1,
    'dislike':-1,
    'comfortable':1,
    'disliked':-1,
    'comfortably':1,
    'disorganized':-1,
    'comforting':1,
    'displeased':-2,
    'coming-along':1,
    'disregarded':-2,
    'committed':2,
    'disrespected':-2,
    'competent':1,
    'disrespectful':-2,
    'competitive':2,
    'dissatisfied':-1,
    'concrete':1,
    'embellish':-2,
    'confident':1,
    'expensive':-1,
    'consistent':1,
    'extortion':-3,
    'consistently':1,
    'fastidious':-2,
    'correctly':1,
    'fault':-1,
    'cost-effective':2,
    'frustrating':-2,
    'creative':2,
    'hard':-1,
    'hard-coded': -1,
    'humble':-2,
    'diligent':2,
    'inactive':-1,
    'drastically':3,
    'inadequate':-1,
    'easily':1,
    'incapable':-1,
    'easy-to-use':2,
    'incompetent':-2,
    'enhance':1,
    'incomplete':-1,
    'essential':1,
    'indifferent':-1,
    'excellent':2,
    'ineffective':-2,
    'exceptional':3,
    'insecure':-2,
    'extensive':2,
    'insignificant':-1,
    'extraordinary':3,
    'insufficient':-1,
    'fabulous':3,
    'intangible':-1,
    'fantastic':2,
    'intimidated':-3,
    'fine':1,
    'lacking':-1,
    'fiscally-responsible':1,
    'low-cost':-1,
    'flexible':2,
    'maliciously':-3,
    'fresh':1,
    'misaligned':-1,
    'friendly':1,
    'nonprofit':-1,
    'genuine':1,
    'nontraditional':-1,
    'good-quality':1,
    'off-putting':-2,
    'great':3,
    'out-of-date':-2,
    'happy':1,
    'outrageous':-3,
    'heartfelt':1,
    'over-diluted':-2,
    'heavy-hitter':1,
    'overpriced':-2,
    'helpful':2,
    'overrated':-2,
    'highly':2,
    'plain':-1,
    'high-quality':3,
    'redefine':-1,
    'holistic':2,
    'reluctant':-1,
    'honest':2,
    'rigorous':-3,
    'ideation':1,
    'schoolish':-1,
    'illustrative':1,
    'seasonal':-1,
    'important':2,
    'shamelessly':-2,
    'impress':2,
    'shoddy':-2,
    'increase':1,
    'simplify':-1,
    'incrementally':1,
    'small':-1,
    'in-depth':2,
    'stringent':-1,
    'inevitably':1,
    'swamped':-2,
    'influential':1,
    'tight':-1,
    'insightful':1,
    'unavailable':-1,
    'integrity':1,
    'unclear':-2,
    'intelligent':2,
    'unfortunately':-1,
    'intently':2,
    'unprofessionalism':-3,
    'interchangeably':1,
    'younger':-1,
    'interesting':1,
    'justified':2,
    'legitimate':1,
    'luxury':3,
    'occasionally':1,
    'open':1,
    'open-minded':1,
    'organically':2,
    'organized':1,
    'outside-the-box':2,
    'participative':1,
    'passionate':2,
    'perfect':3,
    'persistent':2,
    'personable':1,
    'personalized':2,
    'phenomenal':2,
    'positive':1,
    'positively':1,
    'premium':3,
    'preset':1,
    'prestigious':2,
    'professionally':1,
    'quickly':1,
    'receptive':1,
    'refreshed':1,
    'regular':1,
    'reliable':1,
    'responsive':2,
    'revolutionary':3,
    'sensitive':1,
    'significant':2,
    'smart':2,
    'smoothly':1,
    'sophisticated':1,
    'standout':2,
    'straight-up':1,
    'successful':2,
    'supportive':1,
    'surpass':2,
    'thorough':2,
    'timely': 1,
    'manner': 1,
    'top-quality': 3,
    'total': 1,
    'transparent': 1,
    'tremendous': 3,
    'trusting': 2,
    'unique': 3,
    'united': 2,
    'universally': 2,
    'unusual': 1,
    'updated': 1,
    'valuable': 2,
    'well-suited': 1,
    'whimsical': 1,
    'wonderful': 1,
    'worth': 1,
}

INTENSIFIER_VOCABULARY = {
    'hight': (
        'absolutely', 'amazingly', 'at all', 'awfully', 'bitterly', 'certain', 'certainly',
        'completely', 'considerably', 'credible', 'deeply', 'definitely', 'easily',
        'especially', 'exactly', 'exceptionally', 'excessively', 'extremely', 'fully',
        'great', 'highly', 'increasingly', 'incredibly', 'indeed', 'major', 'more', 'most',
        'much', 'nice', 'obviously', 'overwhelming', 'perfectly', 'readily', 'really', 'ridiculously',
        'so', 'specially', 'terrifically', 'total', 'totally', 'true', 'very',
    ),
    'medium': (
        'actually', 'admittedly', 'better', 'clear', 'clearly', 'constantly', 'enough', 'even',
        'frankly', 'good', 'honestly', 'likely', 'lot', 'measurable', 'much ', 'original',
        'positively', 'pretty', 'reasonably', 'specifically', 'truly', 'unexpectedly',
    ),
    'low': (
        'actively', 'actually', 'almost', 'as', 'bad', 'bit', 'complete', 'differently', 'extra',
        'fairly', 'few', 'genuinely', 'huge', 'least', 'little', 'lovely', 'minimal', 'minor',
        'nearly', 'necessary', 'occasionally', 'particularly', 'poorly', 'quite', 'simply',
        'specifically', 'typically',
    )
}

INTENSIFIER_RATES = {
    'hight': 2,
    'medium': 1.5,
    'low': 0.5,
}

INVERTER_VOCABULARY = (
    "least",
    "less",
    "never",
    "no",
    "non",
    "not",
    "nothing",
    "without",
)

ASPECT_CATEGORIES = {
    'common': (
        'advertising and marketing agency', 'branding agency', 'creative agency', 'digital marketing agency',
        'full service digital agency', 'social media marketing agency', 'public relations agency',
        'video production agency', 'naming agency',
    ),
    'service lines': (
        'search engine optimization', 'pay per click', 'social media marketing', 'branding', 'web design',
        'direct marketing', 'advertising', 'video production', 'web development', 'digital strategy',
        'UX/UI design', 'broadcast video advertising', 'radio advertising', 'out of home advertising',
        'print advertising',
    ),
    'service and deliverables': (
        'e-mailing', 'phone call', 'meeting', 'management', 'coordination', 'contact', 'feedback',
    ),
    'scheduling': (
        'on time', 'out of time', 'deadline', 'timeline',
    ),
}